spring:
  application:
    name: mybatis-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      maximum-pool-size: 80
  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: true
