### 상품 생성
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "새 상품",
  "price": 1000,
  "stockQuantity": 10
}

### 상품 단건 조회
GET http://localhost:8080/products/2

### 상품 수정
PATCH http://localhost:8080/products/2
Content-Type: application/json

{
  "name": "상품 수정",
  "price": 2000,
  "stockQuantity": 20
}

### 상품 삭제
DELETE http://localhost:8080/products/2
